name: Daily Portfolio Log

on:
  schedule:
    # Runs at 10:15 UTC (3:45 PM IST) on Weekdays (Mon-Fri)
    # Adjust the cron schedule if you need a different time.
    # Cron format: minute hour day(of_month) month day(of_week)
    - cron: '15 10 * * 1-5'
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  run-daily-logger:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow workflow to checkout code

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your chosen Python version (e.g., 3.10, 3.11)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pro/requirements.txt # Assuming requirements.txt is in the 'pro' folder at the root of your repo

    - name: Create Firebase Service Account Key from Secret
      env:
        FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON_LOGGER }}
      run: |
        echo "Attempting to create Firebase key file for logger..."
        if [ -z "$FIREBASE_KEY_JSON" ]; then
          echo "Error: FIREBASE_SERVICE_ACCOUNT_KEY_JSON_LOGGER secret is not set."
          exit 1
        fi
        # Create the 'pro' directory if it doesn't exist in the runner (it should after checkout)
        mkdir -p pro 
        echo "$FIREBASE_KEY_JSON" > pro/firebase-service-account-key.json
        echo "Firebase key file created at pro/firebase-service-account-key.json"

    - name: Run Daily Portfolio Logger
      # Ensure the path to your script and requirements.txt is correct
      # relative to the root of your GitHub repository.
      run: python pro/daily_portfolio_logger.py